# -*- coding: utf-8 -*-
"""2)diabetes_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVbbAPtlQRVe1IzzvI2FeKVrHWEddTB8
"""
### dataset --> diabetes.csv 

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn import svm

data = pd.read_csv('/content/diabetes.csv')
print(data.head())
data['Outcome'].value_counts()

X = data.drop(columns = 'Outcome', axis = 1)
Y = data['Outcome']
print(X)
print(Y)

scalar = StandardScaler()
scalar.fit(X_train)
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)
print(X_train)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,stratify = Y,random_state = 2)
print(X.shape,X_train.shape,X_test.shape)

model = svm.SVC(kernel = 'linear')
model.fit(X_train,Y_train)

X_train_pred = model.predict(X_train)
train_acc = accuracy_score(X_train_pred,Y_train)
print(train_acc)

