# -*- coding: utf-8 -*-
"""3)house_price_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVwaog5VSzY4ZDg_0Llv98D7kHRYc1S3
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sns
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
import sklearn.datasets

housing_data = sklearn.datasets.fetch_california_housing()

print(housing_data)
df = pd.DataFrame(housing_data.data, columns=housing_data.feature_names)
df.head()

df['price'] = housing_data.target
df.head()

df.isnull().sum()

correlation = df.corr()
plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f', annot=True, annot_kws={'size':8}, cmap='Blues')

X = df.drop(['price'], axis=1)
Y = df['price']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

model = XGBRegressor()
model.fit(X_train,Y_train)

X_train_pred = model.predict(X_train)
train_mae = metrics.mean_absolute_error(Y_train,X_train_pred)
train_mse = metrics.mean_squared_error(Y_train,X_train_pred)

print('X_train_prediction: ',X_train_pred)
print('Training MAE: ',train_mae)
print('Training MSE: ',train_mse)

