# -*- coding: utf-8 -*-
"""4)Fake_news_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LS-cClEC_VgznZ4c_dBVtikD_CMdS7Ig
"""

import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')
print(stopwords.words('english'))

import kagglehub

path = kagglehub.dataset_download("algord/fake-news")

print("Path to dataset files:", path)

import os
dataset_files = os.listdir(path)
csv_file = [f for f in dataset_files if f.endswith('.csv')][0]

full_csv_path = os.path.join(path, csv_file)

df = pd.read_csv(full_csv_path)

df.head()

"""### Data Preprocessing

First, I will combine the `title` column into a new `content` column. Then I will clean the text by removing non-alphabetic characters, converting to lowercase, removing stopwords, and applying stemming.
"""

print(df.isnull().sum())

df['title'] = df['title'].fillna('')

df['content'] = df['title']

port_stem = PorterStemmer()

def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

df['content'] = df['content'].apply(stemming)

X = df['content'].values
Y = df['real'].values

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=42)

model = LogisticRegression(solver='liblinear')
model.fit(X_train, Y_train)

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print(f'Accuracy score on the training data: {training_data_accuracy}')

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(f'Accuracy score on the test data: {test_data_accuracy}')