# -*- coding: utf-8 -*-
"""5)loan_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEiyQpDPonHUClL2JFHsQqraN9GPNijN
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm

from sklearn.preprocessing import StandardScaler

loan_dataset = pd.read_csv('/content/loan dataset.csv')
loan_dataset.head()

loan_dataset.isnull().sum()

loan_dataset = loan_dataset.dropna()
loan_dataset.drop(columns=['Loan_ID'],inplace=True)
loan_dataset.isnull().sum()

loan_dataset['Dependents'].value_counts()

loan_dataset = loan_dataset.replace(to_replace='3+', value=4)
loan_dataset['Dependents'].value_counts()

sns.countplot(x='Education',hue='Loan_Status',data=loan_dataset)

sns.countplot(x='Married',hue='Loan_Status',data=loan_dataset)

loan_dataset.replace({'Married':{'Yes':1,'No':0},
                      'Education':{'Graduate':1, 'Not Graduate':0},
                      'Self_Employed':{'Yes':1, 'No':0},
                      'Gender':{'Male':1,'Female':0},
                      'Property_Area':{'Rural':0, 'Semiurban':1, 'Urban':2},
                      'Loan_Status':{'N':0, 'Y':1} },inplace=True)

X = loan_dataset.drop(columns=['Loan_Status'],axis=1)
Y = loan_dataset['Loan_Status']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=2)
print(X.shape,X_train.shape,X_test.shape)

"""### Feature Scaling for Numerical Features

Support Vector Machines are sensitive to the scale of numerical features.Use `StandardScaler` to standardize features by removing the mean and scaling to unit variance.
"""

numerical_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']

scaler = StandardScaler()

X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

print("X_train after scaling numerical features:")
display(X_train.head())
print("X_test after scaling numerical features:")
display(X_test.head())

"""Training the Model :

Support Vector Machine
"""

model = svm.SVC(kernel='linear')
model.fit(X_train,Y_train)

X_train_pred = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train,X_train_pred)
print('Accuracy on training data : ',training_data_accuracy)

X_test_pred = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test,X_test_pred)
print('Accuracy on test data : ',test_data_accuracy)

"""### Making a Predictive System"""

def predict_loan_status(gender, married, dependents, education, self_employed,
                        applicant_income, coapplicant_income, loan_amount,
                        loan_amount_term, credit_history, property_area):
    data = {
        'Gender': [gender],
        'Married': [married],
        'Dependents': [dependents],
        'Education': [education],
        'Self_Employed': [self_employed],
        'ApplicantIncome': [applicant_income],
        'CoapplicantIncome': [coapplicant_income],
        'LoanAmount': [loan_amount],
        'Loan_Amount_Term': [loan_amount_term],
        'Credit_History': [credit_history],
        'Property_Area': [property_area]
    }
    input_df = pd.DataFrame(data)

    input_df['Dependents'] = input_df['Dependents'].replace('3+', '4').astype(int)

    input_df.replace({
        'Married': {'Yes': 1, 'No': 0},
        'Education': {'Graduate': 1, 'Not Graduate': 0},
        'Self_Employed': {'Yes': 1, 'No': 0},
        'Gender': {'Male': 1, 'Female': 0},
        'Property_Area': {'Rural': 0, 'Semiurban': 1, 'Urban': 2}
    }, inplace=True)

    # Make prediction
    prediction = model.predict(input_df)

    if (prediction[0] == 1):
        return 'Loan Approved'
    else:
        return 'Loan Not Approved'

example_prediction = predict_loan_status(
    gender='Female', married='Yes', dependents='1', education='Not Graduate', self_employed='No',
    applicant_income=53, coapplicant_income=158, loan_amount=920008,
    loan_amount_term=36, credit_history=0.0, property_area='Rural'
)

print(example_prediction)

"""The previous prediction function did not account for feature scaling, which was applied to the training data. The updated `predict_loan_status` function below includes the necessary scaling of numerical features using the fitted `scaler`."""

def predict_loan_status_scaled(gender, married, dependents, education, self_employed,
                               applicant_income, coapplicant_income, loan_amount,
                               loan_amount_term, credit_history, property_area):

    data = {
        'Gender': [gender],
        'Married': [married],
        'Dependents': [dependents],
        'Education': [education],
        'Self_Employed': [self_employed],
        'ApplicantIncome': [applicant_income],
        'CoapplicantIncome': [coapplicant_income],
        'LoanAmount': [loan_amount],
        'Loan_Amount_Term': [loan_amount_term],
        'Credit_History': [credit_history],
        'Property_Area': [property_area]
    }
    input_df = pd.DataFrame(data)

    input_df['Dependents'] = input_df['Dependents'].replace('3+', '4').astype(int)

    input_df.replace({
        'Married': {'Yes': 1, 'No': 0},
        'Education': {'Graduate': 1, 'Not Graduate': 0},
        'Self_Employed': {'Yes': 1, 'No': 0},
        'Gender': {'Male': 1, 'Female': 0},
        'Property_Area': {'Rural': 0, 'Semiurban': 1, 'Urban': 2}
    }, inplace=True)

    # Apply the same scaling to numerical features as used in training
    input_df[numerical_cols] = scaler.transform(input_df[numerical_cols])

    # Make prediction
    prediction = model.predict(input_df)

    if (prediction[0] == 1):
        return 'Loan Approved'
    else:
        return 'Loan Not Approved'

example_prediction_scaled = predict_loan_status_scaled(
    gender='Female', married='Yes', dependents='1', education='Not Graduate', self_employed='No',
    applicant_income=53, coapplicant_income=158, loan_amount=920008,
    loan_amount_term=36, credit_history=0.0, property_area='Rural'
)

print(example_prediction_scaled)

