# -*- coding: utf-8 -*-
"""6)WIne_quaility_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yER3Jn3F_hWDyiYKFwBwIDRLCNRF8opv
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

dataset = pd.read_csv ('/content/winequality-red.csv')
dataset.head()

dataset.isnull().sum()

sns.catplot(x='quality', data=dataset, kind='count')

correlation = dataset.corr()
plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f', annot=True, annot_kws={'size':8}, cmap='Blues')

X = dataset.drop('quality', axis=1)
Y = dataset['quality'].apply(lambda y: 1 if y>=7 else 0)
# print(X)
# print(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

model = RandomForestClassifier()
model.fit(X_train, Y_train)

X_test_pred = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_pred, Y_test)
print("test_data_accuracy: ",test_data_accuracy)

"""## building a predictive function"""

ip = input("enter the values: ")
ip = ip.split(',')
ip = np.array(ip)

ip = ip.reshape(1,-1)

prediction = model.predict(ip)
print(prediction)
if prediction[0] == 1:
  print("good quality wine")
else:
  print("bad quality wine")

