# -*- coding: utf-8 -*-
"""8)Gold_price_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiB16lUpxkDi1uffuw25QqWyq2Z8mMVT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

dataset = pd.read_csv('/content/gld_price_data.csv')
dataset.tail()

dataset.isnull().sum()

dataset = dataset.drop(['Date'],axis=1)
dataset.head()

correlation = dataset.corr()

plt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True,square=True,fmt='.1f',annot=True,annot_kws={'size':8},cmap='Blues')

sns.distplot(dataset['GLD'],color='red')

X = dataset.drop(['GLD'],axis=1)
Y = dataset['GLD']
print(X)
print(Y)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

model = RandomForestRegressor(n_estimators=200)
model.fit(X_train,Y_train)

test_data_prediction = model.predict(X_test)
print("test data prediction: ",test_data_prediction)

r2_error = metrics.r2_score(Y_test,test_data_prediction)
print("R squared error: ",r2_error)

y_test = list(Y_test)
plt.figure(figsize=(12, 6))
plt.plot(y_test,color='blue',label='Actual Value')
plt.plot(test_data_prediction,color='green',label='Predicted Value')
plt.title('Actual Price vs Predicted Price')
plt.xlabel('Number of values')
plt.ylabel('GLD Price')
plt.legend()
plt.show()



plt.figure(figsize=(18, 6))

# Subplot 1: Actual Price vs Predicted Price
plt.subplot(1, 3, 1)
plt.plot(y_test, color='blue', label='Actual Value')
plt.plot(test_data_prediction, color='green', label='Predicted Value')
plt.title('Actual vs Predicted Price')
plt.xlabel('Number of values')
plt.ylabel('GLD Price')
plt.legend()

# Subplot 2: Actual Gold Price
plt.subplot(1, 3, 2)
plt.plot(y_test, color='blue', label='Actual Value')
plt.title('Actual Gold Price')
plt.xlabel('Number of values')
plt.ylabel('GLD Price')
plt.legend()

# Subplot 3: Predicted Gold Price
plt.subplot(1, 3, 3)
plt.plot(test_data_prediction, color='green', label='Predicted Value')
plt.title('Predicted Gold Price')
plt.xlabel('Number of values')
plt.ylabel('GLD Price')
plt.legend()

plt.tight_layout()
plt.show()

