# -*- coding: utf-8 -*-
"""9)Heart_disease_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117N5sEotwm0Gts9woCrn_rJwrL-qDjQ-
"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import sklearn.metrics
from sklearn.metrics import accuracy_score

dataset = pd.read_csv('/content/heart_disease_data.csv')
dataset.head()

dataset.isnull().sum()

dataset['target'].value_counts()

X = dataset.drop(columns='target', axis=1)
Y = dataset['target']
print(X)
print(Y)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
print(X.shape,X_train.shape,X_test.shape)

model = LogisticRegression()
model.fit(X_train,Y_train)

test_data_accuracy = model.score(X_test,Y_test)
print('Accuracy on test data : ',test_data_accuracy)

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)
print('Accuracy on training data : ',training_data_accuracy)

input_data = (41,0,1,130,204,0,0,172,0,1.4,2,0,2)

input_data = np.asarray(input_data)
input_data = input_data.reshape(1,-1)

prediction = model.predict(input_data)
print(prediction)

if (prediction[0]==0):
  print('The person does not have a heart disease')
else:
  print('The person has a heart disease')

